#define HORN            12
#define COMPRESSOR      11
#define PRESSURE        A16
#define UP_LED          24
#define UP_SWITCH       25
#define DOWN_LED        26
#define DOWN_SWITCH     27
#define SELECT_LED      28
#define SELECT_SWITCH   29
#define BACK_LED        30
#define BACK_SWITCH     31
#define LCD_VO          A22
#define LCD_RS          13
#define LCD_RW          14
#define LCD_E           15
#define LCD_DB0         16
#define LCD_DB1         17
#define LCD_DB2         18
#define LCD_DB3         19
#define LCD_DB4         20
#define LCD_DB5         21
#define LCD_DB6         22
#define LCD_DB7         23
#define LCD_BL_RED      36
#define LCD_BL_BLUE     37
#define LCD_BL_GREEN    38
